import { useCallback } from "react";
import { Link, useParams } from "react-router-dom";

import { getIncident, listIncidentActivity, listIncidentEvidence, listIncidentHypotheses } from "../api/incidents";
import { ActivityTimeline } from "../components/ActivityTimeline";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";
import { EvidenceTable, type EvidenceView } from "../components/EvidenceTable";
import { HypothesisCard } from "../components/HypothesisCard";
import { Icon } from "../components/Icon";
import { LoadingState } from "../components/LoadingState";
import { PageHeader } from "../components/PageHeader";
import { Panel } from "../components/Panel";
import { SectionHeading } from "../components/SectionHeading";
import { SeverityBadge, StatusBadge } from "../components/StatusBadge";
import { useAsyncData } from "../hooks/useAsyncData";
import { formatDateTime, humanize } from "../lib/format";
import type { ActivityEvent, Evidence, Hypothesis, Incident } from "../types";

interface InvestigationData {
  incident: Incident;
  activity: ActivityEvent[];
  evidence: Evidence[];
  hypotheses: Hypothesis[];
}

function toEvidenceView(item: Evidence): EvidenceView {
  return { id: item.id, incidentId: item.incident_id, incidentTitle: "Live incident record", type: item.type, source: item.source, timestamp: item.timestamp, summary: item.summary, relevance: item.relevance, status: "recorded" };
}

export function InvestigationDetailPage() {
  const { incidentId } = useParams<{ incidentId: string }>();
  const loader = useCallback(async (): Promise<InvestigationData> => {
    if (!incidentId) throw new Error("No incident id was supplied.");
    const [incident, activity, evidence, hypotheses] = await Promise.all([
      getIncident(incidentId),
      listIncidentActivity(incidentId),
      listIncidentEvidence(incidentId),
      listIncidentHypotheses(incidentId)
    ]);
    return { incident, activity, evidence, hypotheses };
  }, [incidentId]);
  const { data, isLoading, error, reload } = useAsyncData(loader, [incidentId]);

  if (isLoading && !data) return <LoadingState label="Loading investigation workspace…" rows={6} />;
  if (error && !data) return <ErrorState title="Investigation record unavailable" description={error} onRetry={reload} />;
  if (!data) return null;
  const { incident, activity, evidence, hypotheses } = data;

  return (
    <section className="page-section">
      <Link className="back-link" to="/investigation"><Icon name="arrow" size={14} /> Back to investigation queue</Link>
      <PageHeader eyebrow={`INVESTIGATION / ${incident.id.slice(0, 8)}`} title={incident.title} description="Structured evidence and hypothesis surfaces for one incident. Investigation execution is not enabled in Phase 2." meta={<><Icon name="clock" size={13} /> Intake received {formatDateTime(incident.created_at)}</>} actions={<div className="detail-badges"><SeverityBadge severity={incident.severity} /><StatusBadge value={incident.agent_state} label={humanize(incident.agent_state)} /></div>} />
      <div className="investigation-banner"><div className="banner-icon"><Icon name="investigation" size={18} /></div><div><strong>Investigation not started</strong><span>The Phase 1 backend has recorded intake only. Evidence and hypotheses below are real records when available; no inference is generated by this screen.</span></div></div>

      <div className="detail-grid detail-grid-wide">
        <Panel>
          <SectionHeading eyebrow="EVIDENCE COLLECTED" title={`${evidence.length} evidence records`} description="Source records attached to this incident." />
          {evidence.length ? <EvidenceTable records={evidence.map(toEvidenceView)} /> : <EmptyState title="No evidence available" description="No evidence has been recorded for this incident." />}
        </Panel>
        <Panel>
          <SectionHeading eyebrow="HYPOTHESES" title={`${hypotheses.length} structured hypotheses`} description="Confidence and validation status only; private reasoning is not displayed." />
          {hypotheses.length ? <div className="hypothesis-stack">{hypotheses.map((hypothesis) => <HypothesisCard hypothesis={hypothesis} key={hypothesis.id} />)}</div> : <EmptyState title="No hypotheses available" description="Hypothesis generation has not been recorded for this incident." />}
        </Panel>
      </div>

      <Panel>
        <SectionHeading eyebrow="OBSERVABLE ACTIVITY" title="Investigation activity" description="Only auditable backend events are rendered." />
        <ActivityTimeline events={activity} />
      </Panel>
    </section>
  );
}
