import { useCallback } from "react";
import { Link } from "react-router-dom";

import { listActions } from "../api/actions";
import { listPhase8Verifications, getVerificationSummary } from "../api/verification";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";
import { Icon } from "../components/Icon";
import { LoadingState } from "../components/LoadingState";
import { MetricCard } from "../components/MetricCard";
import { PageHeader } from "../components/PageHeader";
import { Panel } from "../components/Panel";
import { SectionHeading } from "../components/SectionHeading";
import { StatusBadge } from "../components/StatusBadge";
import { useAsyncData } from "../hooks/useAsyncData";
import { formatDateTime, humanize } from "../lib/format";
import type { ControlledAction, Phase8VerificationRecord, Phase8VerificationSummary } from "../types";

interface VerificationData {
  verifications: Phase8VerificationRecord[];
  actions: ControlledAction[];
  summary: Phase8VerificationSummary;
}

export function VerificationPage() {
  const loader = useCallback(async (): Promise<VerificationData> => {
    const [verifications, actions, summary] = await Promise.all([
      listPhase8Verifications(),
      listActions(),
      getVerificationSummary()
    ]);
    return { verifications, actions, summary };
  }, []);
  const { data, isLoading, error, reload } = useAsyncData(loader);

  if (isLoading && !data) return <LoadingState label="Loading verification records…" rows={6} />;
  if (error && !data) return <ErrorState title="Verification center unavailable" description={error} onRetry={reload} />;

  const verifications = data?.verifications ?? [];
  const actions = data?.actions ?? [];
  const summary = data?.summary;

  return (
    <section className="page-section">
      <PageHeader
        eyebrow="ACTION / PHASE 8 RELIABILITY"
        title="Verification center"
        description="Execution completion is separate from proof. Every record below is generated by the server-side verification engine and remains bound to one incident and one action."
        meta={<><Icon name="shield" size={13} /> SIMULATED / CONTROLLED DEMONSTRATION <span className="meta-separator">·</span> Evidence is provenance-labeled</>}
        actions={<button className="secondary-button" type="button" onClick={reload} disabled={isLoading}><Icon name="refresh" size={14} /> {isLoading ? "Refreshing…" : "Refresh records"}</button>}
      />

      <div className="metric-grid metric-grid-command verification-metrics">
        <MetricCard label="Total proofs" value={summary?.total ?? "—"} detail={summary?.message ?? "Server summary unavailable"} tone="info" icon={<Icon name="verification" size={16} />} />
        <MetricCard label="Passed" value={summary?.passed ?? "—"} detail="Resolution-eligible only after proof gate" tone="success" icon={<Icon name="check" size={16} />} />
        <MetricCard label="Recovery required" value={summary?.recovery_required ?? "—"} detail="Bounded retry or registered rollback review" tone="warning" icon={<Icon name="history" size={16} />} />
        <MetricCard label="Requires human" value={summary?.requires_human ?? "—"} detail="Execution or evidence could not prove recovery" tone={summary?.requires_human ? "critical" : "default"} icon={<Icon name="incidents" size={16} />} />
      </div>

      <Panel>
        <SectionHeading
          eyebrow="SERVER-OWNED REGISTER"
          title="Expected versus actual proof"
          description="Confidence is a deterministic factor score, not model authority. Open a record to inspect checks, trust labels, evidence provenance, and the append-only timeline."
          action={<StatusBadge value={verifications.length ? "recorded" : "not-recorded"} label={verifications.length ? `${verifications.length} records` : "No records"} dot />}
        />
        {verifications.length ? (
          <div className="verification-list">
            {verifications.map((record) => (
              <div className="verification-row phase8-verification-row" key={record.verification_id}>
                <div className="verification-title">
                  <span className="verification-icon"><Icon name="verification" size={16} /></span>
                  <div>
                    <Link to={`/verification/${record.verification_id}`}><strong>{humanize(record.strategy[0] ?? "Verification")}</strong></Link>
                    <span>{record.verification_id.slice(0, 12)} · Incident {record.incident_id.slice(0, 8)} · {formatDateTime(record.updated_at)}</span>
                  </div>
                </div>
                <div className="verification-checks">
                  <span>Checks <b>{record.checks.length}</b></span>
                  <span>Attempt <b>{record.attempt}/{record.max_attempts}</b></span>
                  <span>Confidence <b>{Math.round(record.confidence * 100)}%</b></span>
                </div>
                <StatusBadge value={record.status} label={humanize(record.status)} dot />
              </div>
            ))}
          </div>
        ) : <EmptyState title="No verification records" description="A record appears after a known controlled action is bound to the Phase 8 verification service." />}
      </Panel>

      <Panel>
        <SectionHeading
          eyebrow="ACTION BINDINGS"
          title="Execution register"
          description="The action register is shown beside verification so an operator can distinguish completed execution, rollback, escalation, and proven resolution."
          action={<StatusBadge value={actions.length ? "recorded" : "not-recorded"} label={actions.length ? `${actions.length} actions` : "No actions"} dot />}
        />
        {actions.length ? (
          <div className="verification-list">
            {actions.map((action) => (
              <div className="verification-row" key={action.action_id}>
                <div className="verification-title"><span className="verification-icon"><Icon name="remediation" size={16} /></span><div><Link to={`/remediation/${action.action_id}`}><strong>{humanize(action.action_name)}</strong></Link><span>Incident {action.incident_id.slice(0, 8)} · {formatDateTime(action.updated_at)}</span></div></div>
                <div className="verification-checks"><span>Execution <b>{humanize(action.status)}</b></span><span>Proof <b>{humanize(action.verification_status)}</b></span></div>
                <StatusBadge value={action.verification_status} label={humanize(action.verification_status)} dot />
              </div>
            ))}
          </div>
        ) : <EmptyState compact title="No controlled actions" description="No registered action has executed through the approval gate." />}
      </Panel>
      <div className="verification-legend"><StatusBadge value="server-owned" label="Server-owned" dot /><span>The frontend can request a bounded run, retry, or cancellation; it cannot submit expected state, actual state, trust, confidence, risk, approval, or resolution.</span></div>
    </section>
  );
}
